# -*- coding: utf-8 -*-
"""edudatahelper.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hJ7Bq_Ny8tg7crNWjNR7RiYO2wrm6TUR
"""

import pandas as pd
import requests
import json
import csv

#Initializing variables for Michigan like ISD, years, and categories
isds = {
    "Allegan Area Educational Service Agency (03)": "63",
    "Alpena-Montmorency-Alcona ESD (04)": "64",
    "Barry ISD (08)": "65",
    "Bay-Arenac ISD (09)": "66",
    "Berrien RESA (11)": "67",
    "Branch ISD (12)": "68",
    "C.O.O.R. ISD (72)": "69",
    "Calhoun Intermediate School District (13)": "70",
    "Charlevoix-Emmet ISD (15)": "71",
    "Cheb-Otsego-Presque Isle ESD (16)": "72",
    "Clare-Gladwin Regional Education Service District (18)": "73",
    "Clinton County RESA (19)": "74",
    "Copper Country ISD (31)": "75",
    "Delta-Schoolcraft ISD (21)": "76",
    "Dickinson-Iron ISD (22)": "77",
    "Eastern Upper Peninsula ISD (17)": "78",
    "Eaton RESA (23)": "79",
    "Genesee ISD (25)": "80",
    "Gogebic-Ontonagon ISD (27)": "81",
    "Gratiot-Isabella RESD (29)": "82",
    "Heritage Southwest Intermediate School District (14)": "93",
    "Hillsdale ISD (30)": "83",
    "Huron ISD (32)": "84",
    "Ingham ISD (33)": "85",
    "Ionia ISD (34)": "86",
    "Iosco RESA (35)": "87",
    "Jackson ISD (38)": "88",
    "Kalamazoo RESA (39)": "89",
    "Kent ISD (41)": "90",
    "Lapeer ISD (44)": "91",
    "Lenawee ISD (46)": "92",
    "Livingston ESA (47)": "94",
    "Macomb ISD (50)": "95",
    "Manistee ISD (51)": "96",
    "Marquette-Alger Regional Education Service Agency (52)": "97",
    "Mecosta-Osceola ISD (54)": "99",
    "Menominee ISD (55)": "100",
    "Midland County Educational Service Agency (56)": "101",
    "Monroe ISD (58)": "102",
    "Montcalm Area ISD (59)": "103",
    "Muskegon Area ISD (61)": "104",
    "Newaygo County RESA (62)": "105",
    "Northwest Education Services (28)": "115",
    "Oakland Schools (63)": "106",
    "Oceana Intermediate School District (64) (closed)": "107",
    "Ottawa Area ISD (70)": "108",
    "Saginaw ISD (73)": "109",
    "Sanilac ISD (76)": "110",
    "Shiawassee Regional ESD (78)": "111",
    "St. Clair County RESA (74)": "112",
    "St. Joseph County ISD (75)": "113",
    "State of Michigan (84)": "114",
    "Tuscola ISD (79)": "116",
    "Van Buren ISD (80)": "117",
    "Washtenaw ISD (81)": "118",
    "Wayne RESA (82)": "119",
    "West Shore Educational Service District (53)": "98",
    "Wexford-Missaukee ISD (83)": "120"
}

years = {
    "2025-26": "27",
    "2024-25": "26",
    "2023-24": "25",
    "2022-23": "24",
    "2021-22": "23",
    "2020-21": "22",
    "2019-20": "21",
    "2018-19": "20",
    "2017-18": "19",
    "2016-17": "18",
    "2015-16": "15",
    "2014-15": "14",
    "2013-14": "13",
    "2012-13": "12",
    "2011-12": "11",
    "2010-11": "10",
    "2009-10": "9",
    "2008-09": "8",
    "2007-08": "6",
    "2006-07": "5",
    "2005-06": "4",
    "2004-05": "3",
    "2003-04": "2",
    "2002-03": "1"
}

data_file_strings = [
    "~AssessmentParticipationCrossTab",
    "~Section31a2",
    "~CollegeReadiness2",
    "~Grades38Assessments2",
    "~Grades38StudentBreakdown",
    "~HighSchoolAssessments",
    "~HighSchoolAssessmentsStudentBreakdown",
    "~MiAccessELAProficiencyCrossTab",
    "~MiAccessMathProficiencyCrossTab",
    "~MSTEPELAProficiencyCrossTab",
    "~MSTEPMathProficiencyCrossTab",
    "~PSATProficiencyEBRWCrossTab",
    "~PSATProficiencyMathCrossTab",
    "~SATProficiencyEBRWCrossTab",
    "~SATProficiencyMathCrossTab",
    "~StudentGrowth",
    "~StudentGrowthCrossTab",
    "~Top30Bottom30",

    "EducationalEntityMaster",
    "LegislativeDistrict",

    "~EarlyChildhoodCount2",
    "~EarlyChildhoodAttendance",
    "KindergartenCount",
    "~EarlyChildhoodPathways2",
    "~EarlyChildhoodParticipantAssessments",
    "~EarlyChildhoodParticipantAssessmentsStatewide",

    "~WidaAccessPerformance",
    "~EnglishLearnerStudentGrowth",

    "~FinancialTransparencyDashboard",

    "ParentDashboard",
    "SchoolServicesAndOfferings",

    "~IheEnrollmentByHighSchool2",
    "~CollegeEnrollmentDestination",
    "~PscProgress",
    "~IheRemedialCoursesByHighSchool2",

    "~EarlyChildhoodContinuityComparisons",
    "~EarlyChildhoodContinuityServicePathways",
    "SpecialEducationDashboard",

    "~NewEducatorEffectiveness",
    "StaffCount3",

    "~StudentCountAttendance",
    "~GraduationDropout3",
    "~StudentCountStudentMobility",
    "ResidentNonResident",
    "StudentCountRetainedInGrade2",
    "StudentCount2",
    "StudentCountCrosstab"
]

URL = "https://www.mischooldata.org/umbraco/surface/RedesignWebService/CreateK12SchoolDataFile"

def get_datasets(isd_id, year_id, data_file, email_address):
  payload = {
    "dataFileString": data_file,
    "emailAddress": email_address,
    "schoolYearId": year_id,
    "locationId": f"I,{isd_id},0,0"
      }

  headers = {
        "Content-Type": "application/x-www-form-urlencoded; charset=UTF-8",
        "X-Requested-With": "XMLHttpRequest",
        "Origin": "https://www.mischooldata.org",
        "Referer": "https://www.mischooldata.org/k-12-data-files/"
      }

  response = requests.post(URL, data=payload, headers=headers)

  return {
      "status": response.status_code,
      "text": response.text,
      "isd_id": isd_id,
      "year_id": year_id,
      "dataFileString": data_file
  }

def run_api(isd_id, email_address):
  results = []
  for year_name, year_id in years.items():
    for data in data_file_strings:
      result = get_datasets(isd_id, year_id, data, email_address)
      results.append({"isd_id": isd_id, "year_id": year_id, "dataFileString": data, "response": result})

  with open("results.json", "w") as f:
    json.dump(results, f, indent=4)
  return results

'''
The main function, given an email and a list of ISDs, goes through the Michigan department of education website
 and uses its API to request data for all areas in all years and sends them to the email for you to download.
 This program will flood your email with many files, the best course of action is to make a label in gmail for your files,
 so it will all go there.
'''
def main():
  user_email = "exampleemail@gmail.com" #change this to your desired email

  #Define the list of ISD IDs you want to process.
  #For ex: isd_ids_to_process = ["63", "64"]
  #Example - isd 63
  #If you want data from all ISD's get it from ['63', '64', '65', '66', '67', '68', '69', '70', '71', '72', '73', '74', '75', '76', '77', '78', '79', '80', '81', '82', '93', '83', '84', '85', '86', '87', '88', '89', '90', '91', '92', '94', '95', '96', '97', '99', '100', '101', '102', '103', '104', '105', '115', '106', '107', '108', '109', '110', '111', '112', '113', '114', '116', '117', '118', '119', '98', '120']

  isd_ids_to_process = ["119"] #This is wayne county's ISD

  all_results = []
  for isd_id in isd_ids_to_process:
    print(f"Processing all years and data files for ISD: {isd_id}")
    #Run_api goes through all years
    current_isd_results = run_api(isd_id, user_email)
    all_results.extend(current_isd_results)
    print(f"Finished processing ISD: {isd_id}")

  #note that run_api function saves results to a file named 'results.json'
  #For multiple ISDs, you might want to adjust run_api to save to ISD files
  #overwrites results.json with the new results

  return all_results

main()